# Generated by protocol/tools/generate_clients.py. Do not edit manually.
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Protocol

from .validation import (
    ValidationError,
    require_fields,
    validate_clock,
    validate_datetime,
    validate_pose,
    validate_uuid,
)

SAP_VERSION = "0.1.0"


@dataclass(frozen=True)
class ClockQuality:
    clock_id: str
    sync_source: str
    uncertainty_ms: float
    offset_ms: float | None = None
    drift_ppm: float | None = None
    synchronized: bool = False
    extensions: Mapping[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "ClockQuality":
        validate_clock(value)
        known = {"clock_id", "sync_source", "uncertainty_ms", "offset_ms", "drift_ppm", "synchronized"}
        return cls(
            clock_id=value["clock_id"], sync_source=value["sync_source"],
            uncertainty_ms=float(value["uncertainty_ms"]), offset_ms=value.get("offset_ms"),
            drift_ppm=value.get("drift_ppm"), synchronized=value.get("synchronized", False),
            extensions={key: item for key, item in value.items() if key not in known},
        )

    def to_dict(self) -> dict[str, Any]:
        result = asdict(self)
        extensions = result.pop("extensions")
        result.update(extensions)
        return result


@dataclass(frozen=True)
class Pose:
    frame_id: str
    position_m: Mapping[str, float]
    orientation: Mapping[str, float]
    status: str
    confidence: float
    covariance_6x6: tuple[float, ...] | None = None
    child_frame_id: str | None = None
    source: str | None = None
    valid_until: str | None = None
    map_revision: str | None = None
    extensions: Mapping[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "Pose":
        validate_pose(value)
        known = {"frame_id", "position_m", "orientation", "status", "confidence", "covariance_6x6", "child_frame_id", "source", "valid_until", "map_revision"}
        covariance = value.get("covariance_6x6")
        return cls(
            frame_id=value["frame_id"], position_m=value["position_m"], orientation=value["orientation"],
            status=value["status"], confidence=float(value["confidence"]),
            covariance_6x6=None if covariance is None else tuple(covariance),
            child_frame_id=value.get("child_frame_id"), source=value.get("source"),
            valid_until=value.get("valid_until"), map_revision=value.get("map_revision"),
            extensions={key: item for key, item in value.items() if key not in known},
        )

    def to_dict(self) -> dict[str, Any]:
        result = asdict(self)
        extensions = result.pop("extensions")
        result.update(extensions)
        return result


@dataclass(frozen=True)
class SessionRequest:
    peer_id: str
    protocol_versions: tuple[str, ...]
    required_capabilities: tuple[str, ...]
    requested_duration_s: float
    optional_capabilities: tuple[str, ...] = ()

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "SessionRequest":
        require_fields(value, ("peer_id", "protocol_versions", "required_capabilities", "requested_duration_s"), "session")
        duration = float(value["requested_duration_s"])
        if not 0 < duration <= 86400:
            raise ValidationError("session.requested_duration_s: outside (0, 86400]")
        return cls(value["peer_id"], tuple(value["protocol_versions"]), tuple(value["required_capabilities"]), duration, tuple(value.get("optional_capabilities", ())))


@dataclass(frozen=True)
class SessionResponse:
    session_id: str
    selected_protocol_version: str
    accepted_capabilities: tuple[str, ...]
    expires_at: str
    event_cursor: str
    rejected_requirements: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        validate_uuid(self.session_id, "session_id")
        validate_datetime(self.expires_at, "expires_at")


@dataclass(frozen=True)
class CommandRequest:
    command_id: str
    idempotency_key: str
    session_id: str
    type: str
    parameters: Mapping[str, Any]
    deadline: str
    correlation_id: str
    preconditions: Mapping[str, Any]
    causation_id: str | None = None
    dry_run: bool = False

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "CommandRequest":
        require_fields(value, ("command_id", "idempotency_key", "session_id", "type", "parameters", "deadline", "correlation_id", "preconditions"), "command")
        for field_name in ("command_id", "session_id", "correlation_id"):
            validate_uuid(value[field_name], field_name)
        validate_datetime(value["deadline"], "deadline")
        allowed = {"stop", "safe_hold", "move_relative", "rotate_to", "navigate_to", "hold_pose", "emit_acoustic_probe", "set_mode", "look_toward", "express"}
        if value["type"] not in allowed:
            raise ValidationError("command.type: unsupported")
        return cls(value["command_id"], value["idempotency_key"], value["session_id"], value["type"], value["parameters"], value["deadline"], value["correlation_id"], value["preconditions"], value.get("causation_id"), value.get("dry_run", False))


@dataclass(frozen=True)
class CommandStatus:
    command_id: str
    state: str
    updated_at: str
    reason_code: str | None = None
    result: Mapping[str, Any] | None = None


@dataclass(frozen=True)
class EventEnvelope:
    schema_version: str
    event_id: str
    event_type: str
    producer_id: str
    sequence: int
    occurred_at: str
    monotonic_ns: int
    clock: ClockQuality
    payload: Mapping[str, Any]
    session_id: str | None = None
    correlation_id: str | None = None
    causation_id: str | None = None
    extensions: Mapping[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "EventEnvelope":
        require_fields(value, ("schema_version", "event_id", "event_type", "producer_id", "sequence", "occurred_at", "monotonic_ns", "clock", "payload"), "event")
        validate_uuid(value["event_id"], "event_id")
        validate_datetime(value["occurred_at"], "occurred_at")
        if value["sequence"] < 0 or value["monotonic_ns"] < 0:
            raise ValidationError("event sequence and monotonic time must be non-negative")
        known = {"schema_version", "event_id", "event_type", "producer_id", "sequence", "occurred_at", "monotonic_ns", "clock", "payload", "session_id", "correlation_id", "causation_id"}
        return cls(
            value["schema_version"], value["event_id"], value["event_type"], value["producer_id"],
            value["sequence"], value["occurred_at"], value["monotonic_ns"], ClockQuality.from_dict(value["clock"]),
            value["payload"], value.get("session_id"), value.get("correlation_id"), value.get("causation_id"),
            {key: item for key, item in value.items() if key not in known},
        )

    def to_dict(self) -> dict[str, Any]:
        result = asdict(self)
        result["clock"] = self.clock.to_dict()
        extensions = result.pop("extensions")
        result.update(extensions)
        return result


class AgentClient(Protocol):
    def create_session(self, request: SessionRequest) -> SessionResponse: ...
    def submit_command(self, request: CommandRequest) -> CommandStatus: ...
    def events_after(self, cursor: str) -> tuple[EventEnvelope, ...]: ...


class SpatialProviderClient(Protocol):
    def create_session(self, request: SessionRequest) -> SessionResponse: ...
    def submit_observation(self, observation: Mapping[str, Any]) -> str: ...
    def events_after(self, cursor: str) -> tuple[EventEnvelope, ...]: ...
